# script: cp "CNAME" "homework-1/CNAME"

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: 'homework-1'
    on:
        branch: master

after_deploy:
    - |
        curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
          -H "X-Auth-Email: ${CF_EMAIL}" \
          -H "X-Auth-Key: ${CF_API_KEY}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
